services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: rglogs-mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    environment:
      MP_SMTP_DISABLE_RDNS: "true"
    restart: unless-stopped
