-- +migrate Up
ALTER TABLE spell_stats
    ADD COLUMN IF NOT EXISTS min_amount BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS max_amount BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS misses INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS glancing INT NOT NULL DEFAULT 0;
