-- +migrate Up
ALTER TABLE spell_stats
    ADD COLUMN IF NOT EXISTS normal_hits INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS normal_total BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS normal_min BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS normal_max BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS crit_total BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS crit_min BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS crit_max BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS glancing_total BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS glancing_min BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS glancing_max BIGINT NOT NULL DEFAULT 0;
